### PR TITLE
[CFM_25] Develop Landing Page GetInvolved Component

### PR DESCRIPTION
**Pull request by bernardm**

### CODE REVIEW

**Comment by bernardm** [comment]
This can be merged in after cm_52_bm @1jeanpaul1 
```
git checkout dev
git merge --ff-only cfm_52_bm
git merge --ff-only cfm_25_ts
```

**Comment by CollectiveFocus** [comment]
Only have two notes

1. There needs to be some margin on the left and right of the component
Screen Shot 2022-06-09 at 3 09 10 PM

2. This ticket doesn't have a requirement to be responsive, but its good that we started with a responsive friendly design. Just note for a future responsive ticket for desktop. The buttons aren't aligned sometimes depending on how long the text is. 
Screen Shot 2022-06-09 at 2 57 12 PM

**Comment by trillium** [comment]
I will update this ticket with a minimum height for the text area so that they're uniform.

For the spacing on left and right, I had thought that would be handled by the parent container, but I can add add margin to if that's our preferred method

**Comment by CollectiveFocus** [comment]
> I will update this ticket with a minimum height for the text area so that they're uniform.
> 
> For the spacing on left and right, I had thought that would be handled by the parent container, but I can add add margin to if that's our preferred method

Hey @Spiteless, I think it should be handled by the parent container. Do you think adding that margin to the parent container is outside the scope of this ticket?

**Comment by trillium** [comment]
Yes, I think adjustment of the parent container is outside the scope of this ticket.

**Review by 1jeanpaul1 — APPROVED** [review]
Looks good to me

**Pull request merged**
