### PR TITLE
[CFM_102] asset: Update /index page content

### PR DESCRIPTION
**Pull request by bernardm**

### CODE REVIEW

**Comment by CollectiveFocus** [comment]
I think we should try to get as close to the figma design as we can. I like the idea of the text overlay over the background image but it’s a bit hard to read.   

Notes:
1. Button
    * Can we change the button color to `#1543D4` to represent what’s in figma
2. Header “Take what you need Leave what you can”
     * Can we change the font color to `#222222` to represent what’s in figma
     * Can we change the font size to around 46pt to represent what’s in figma
3. The text under the “Take what you need…” header
      * It doesn’t make sense for mobile “click button below”. Let’s try this instead? `“The Community Fridge Map can help you find community fridges containing free food near you. Click the Find A Fridge button for the full map and list of fridges“`. I’ll ask the team what the best wording should be, but this should be good for now?   
4. This is a note to self: We should get a better map image for the landing page

Below is my best attempt at getting the landing page to be close to what's on figma for reference:

Screen Shot 2022-08-25 at 3 56 28 PM

**Comment by CollectiveFocus** [comment]
I think since we centered all the other text we should center ```"The Community Fridge Map can help you find community fridges containing free food near you. Click the Find A Fridge button for the full map and list of fridges."``` What do you think? I think it'll also look better for the desktop version centered

Also could we make the opacity of the background image 0.75? 

Code looks good!

**Review by CollectiveFocus — DISMISSED** [review]
Looks good!

**Review by CollectiveFocus — APPROVED** [review]
LGTM!

**Review by trillium — APPROVED** [review]

**Pull request merged**
